[[plugins]]
repo  = 'fatih/vim-go'
build = 'GoInstallBinaries'
on_ft = ['go']

[[plugins]]
repo  = 'amirh/HTML-AutoCloseTag'
on_ft = ['html']

[[plugins]]
repo  = 'hail2u/vim-css3-syntax'
on_ft = ['html']

[[plugins]]
repo  = 'gorodinskiy/vim-coloresque'
on_ft = ['html']

[[plugins]]
repo  = 'tpope/vim-haml'
on_ft = ['html']

[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo  = 'jelera/vim-javascript-syntax'
on_ft = ['js']

[[plugins]]
repo  = 'davidhalter/jedi-vim'
on_ft = ['py']