---
- hosts: 'local'
  connection: local
  vars:
    brew_taps:
      - garethr/kubeval
      - argoproj/tap
    brew_packages:
      - git
      - tree
      - jq
      - ghq
      - peco
      - fzf
      - zsh
      - zsh-completions
      - libev # Locustで使うために入れている
      - neovim
      - goenv
      - pyenv
      - nodenv
      - tfenv
      - docker
      - docker-clean
      - kubectl
      - kubesec
      - kubectx
      - kubeval
      - txn2/tap/kubefwd
      - kind
      - helm
      - helmfile
      - stern
      - weaveworks/tap/eksctl
      - datawire/blackbird/telepresence
      - fluxctl
      - argoproj/tap/argocd
    brew_cask_packages:
      - google-japanese-ime
      - kindle
      - 1password
      - karabiner-elements
      - docker
      - osxfuse
#      - google-chrome
      - slack
      - zoom
      - spotify
      - notion
    pip3_packages:
      - locustio==0.13.5
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
    - name: Use tap
      homebrew_tap:
        name: "{{ brew_taps }}"
        state: "present"
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_packages }}"
    - name: Update Pip3
      pip:
        name: pip
        executable: pip3
        state: latest
    - name: Install Pip3 Packages
      pip:
        name: "{{ pip3_packages }}"
        executable: pip3
        state: present
