---
- hosts: 'local'
  connection: local
  vars:
    brew_packages:
      - git
      - jq
      - ghq
      - peco
      - fzf
      - zsh
      - zsh-completions
      - neovim
      - goenv
      - pyenv
      - nodenv
      - tfenv
      - awscli
      - docker-clean
      - kubesec
      - kubectx
      - helm
      - kustomize
      - stern
      - weaveworks/tap/eksctl
      - fluxctl
    install_envs:
      - nodenv
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"