---
- hosts: 'local'
  connection: local
  vars:
    brew_taps:
      - garethr/kubeval
    brew_packages:
      - git
      - tree
      - jq
      - ghq
      - peco
      - fzf
      - zsh
      - zsh-completions
      - neovim
      - goenv
      - pyenv
      - nodenv
      - tfenv
      - docker-clean
      - kubesec
      - kubectx
      - kubeval
      - helm
      - stern
      - weaveworks/tap/eksctl
      - fluxctl
    brew_cask_packages:
      - kindle
      - 1password
      - karabiner-elements
      - google-chrome
      - slack
      - zoom
      - notion
  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes
    - name: Use tap
      homebrew_tap:
        name: "{{ brew_taps }}"
        state: "present"
    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
        install_options: "appdir=/Applications"
        accept_external_apps: yes
      with_items: "{{ brew_cask_packages }}"
